apiVersion: apps/v1
kind: Deployment
metadata:
  name: "learn-k8s"
  labels:
    name: "learn-k8s"
spec:
  selector:
    matchLabels:
      app: "learn-k8s"
  replicas: 2
  template:
    metadata:
      labels:
        app: "learn-k8s"
    spec:
      containers:
        - name: "learn-k8s"
          image: "thiagosgdev/learn-k8s:latest"
          envFrom:
            - configMapRef:
                name: learn-k8s-env
          #env:
          #  - name: TEST
          #    valueFrom:
          #      configMapKeyRef:
          #        name: learn-k8s-env
          #        key: NAME
          #  - name: AGE
          #    valueFrom:
          #      configMapKeyRef:
          #        name: learn-k8s-env
          #        key: AGE
