apiVersion: v1
kind: Service
metadata:
  name: learn-k8s
spec:
  selector:
    app: learn-k8s
  type: ClusterIP
  ports:
  - name: learn-k8s-service
    port: 4000
    targetPort: 5000
    protocol: TCP
    env:
      - name: TEST
        value: "IT WORKS!"
